MPESA_CONSUMER_KEY: 'AKLwa0vJiSA478noaN5M2lbl15KKlsG0U2GufQpGFZMTePhP'
MPESA_CONSUMER_SECRET: 'rDEMQ1GQr2hBndqKT6zYk0I0N8ThxJnQXRaAjGNrm8fsr21rmC5zDD39Sqk3qQjL'
MPESA_PASSKEY: 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
MPESA_SHORTCODE: '174379'
MPESA_INITIATOR_NAME: 'testapi'
MPESA_INITIATOR_PASSWORD: 'Safaricom999!*!'
CALLBACK_URL: 'https://14d1-165-90-6-63.ngrok-free.app'
REGISTER_URL: "https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl"